### ISSUE TITLE
App in Loop

### ISSUE THREAD

**Issue by xicovarisco** [clucs123/shopify-react-test-v2#1]
Hey @clucs123,
I've found your app through @katiedavis  profile and decided to give it a go as I've been trying for hours to deploy a React Shopify App on Heroku.
Your code explain a bunch of things for me (quite rookie on Shopify here), so thank you so much.

I just have one little question to ask. I installed it successfully on my shopify store, but it seems to be in loop and I cant find the reason for it. (It's literally your app with my .env keys)

When I try to run it for the first time, the app redirects to my store and from my store to the app and so on..
Steps I did:

1) Cloned your repo
2) Created a .env file
3) Run `yarn build`
4) Submitted it to Heroku (via heroku cli)
5) Got the https://desolate-dusk-53030.herokuapp.com/ as a result
6) Accessed the app
7) Redirected to my shopify store
8) Shopify store redirected to my app
9) Which then redirected back to my store
10) .... and so on

So the question is, do you know what could potentially be going on here?

Thank you in advance.
:)

**Comment by clucs123** [comment]
Hey Francisco,

The first thing I would do is check the "Config Vars" in Heroku match your
.env file? You'll need to change the *HOST *variable to match your Heroku
URL (https://desolate-dusk-53030.herokuapp.com/) instead of localhost.

Once the app is on Heroku your .env file is redundant as it's not uploaded
to Heroku when you submit. You can add the Heroku "Config Vars" in your app
Settings.

Hope this helps.

If you've already tried this let me know and I'll have another look.

Paul Clucas

**Comment by xicovarisco** [comment]
Hey @clucs123 
Thanks for your prompt answer.

I’ve tried that and it doesn’t seem to have resolved the problem.
These are my heroku config vars:
![23CA46A7-6F54-460E-9EDB-1628BDD48402](https://user-images.githubusercontent.com/2739233/76153834-b5c8c100-611d-11ea-9808-b218b0743489.png)

**Comment by TomGranot** [comment]
@xicovarisco for what it's worth, I never configured the `HOST` in my local `.env` var or in the Heroku env vars, and my app worked fine on Heroku.

Note that https://github.com/clucs123/shopify-react-test-v2/blob/d00cb50806241fa278fef93a1665e304653319e3/server/server.js#L19, which is where the environment variables are being extracted from the environment and pulled into the app, makes no mention of `HOST`. 

If that would solve the problem that would be hella interesting, since that would mean something else in the code (maybe Shopify's own `shopify-koa-auth` makes use of the `HOST` environment variable, or something quirky like that).

if you end up getting really stuck ping me back here and I'll try to repro on a fresh dyno, see what gives.

**Comment by xicovarisco** [comment]
Hey @tomgs, about the HOST variable.. that's what I thought. :) Thanks for clarifying.

I tried running it again and it didn't work :( Still stuck on the redirect problem.
I'm starting to think that it's a problem with Shopify itself.

Would you be able to give it a go and try to run on a fresh dyno?

Cheers

**Comment by clucs123** [comment]
This repo was just a barebones project I did for Shopify support to highlight an issue I was having at the time. I can't find the local copy of this repo so I can't check the .env vars I used. I usually use a HOST variable for my Shopify apps for GraphQl etc but it seems not in this project. 

Have you run "heroku logs --tail" in the CLI while the app is authenticating? Any console.logs etc you have will appear in the logs and also any exceptions.

**Comment by xicovarisco** [comment]
Good to know @clucs123. Didn't know about that.
Couldn't find anything very helpful on that.

`2020-03-08T11:38:28.981897+00:00 heroku[router]: at=info method=GET path="/?hmac=755309c403758b2185e7fa6096bddca7ca5b75a1050fbc52f7a3ede04136530d&locale=en&session=9b31f483a771b5de57c2979ec71eb81d0d55b79371fd1f853ab703febb05d2a2&shop=corporate-marquees.myshopify.com&timestamp=1583667505" host=desolate-dusk-53030.herokuapp.com request_id=1654d34d-2da8-4ca7-872f-4d89cd158e3d fwd="120.22.148.184" dyno=web.1 connect=0ms service=2ms status=302 bytes=311 protocol=https
2020-03-08T11:38:29.543242+00:00 heroku[router]: at=info method=GET path="/auth?shop=corporate-marquees.myshopify.com" host=desolate-dusk-53030.herokuapp.com request_id=4740a77b-5c90-4b3f-9d88-906384fbeae7 fwd="120.22.148.184" dyno=web.1 connect=0ms service=2ms status=200 bytes=1398 protocol=https
2020-03-08T11:38:30.357584+00:00 heroku[router]: at=info method=GET path="/auth/inline?shop=corporate-marquees.myshopify.com" host=desolate-dusk-53030.herokuapp.com request_id=b90fbf67-1849-420b-a0ca-a9c68c118cc0 fwd="120.22.148.184" dyno=web.1 connect=0ms service=7ms status=302 bytes=1482 protocol=https
2020-03-08T11:38:33.123065+00:00 app[web.1]: ctx.session Session {
2020-03-08T11:38:33.123078+00:00 app[web.1]: _sessCtx: ContextSession {
2020-03-08T11:38:33.123079+00:00 app[web.1]: ctx: {
2020-03-08T11:38:33.123080+00:00 app[web.1]: request: [Object],
2020-03-08T11:38:33.123080+00:00 app[web.1]: response: [Object],
2020-03-08T11:38:33.123080+00:00 app[web.1]: app: [Object],
2020-03-08T11:38:33.123088+00:00 app[web.1]: originalUrl: '/auth/callback?code=7f90a7c93ec4bdab5a163efe0f6674e9&hmac=74538170ef27af96b16b4b071949498c668615c1fe2a2e5c74af5b21d4c5d95f&shop=corporate-marquees.myshopify.com&state=158366751035400&timestamp=1583667512',
2020-03-08T11:38:33.123089+00:00 app[web.1]: req: '<original node req>',
2020-03-08T11:38:33.123090+00:00 app[web.1]: res: '<original node res>',
2020-03-08T11:38:33.123090+00:00 app[web.1]: socket: '<original node socket>'
2020-03-08T11:38:33.123090+00:00 app[web.1]: },
2020-03-08T11:38:33.123091+00:00 app[web.1]: app: { subdomainOffset: 2, proxy: false, env: 'production' },
2020-03-08T11:38:33.123091+00:00 app[web.1]: opts: {
2020-03-08T11:38:33.123092+00:00 app[web.1]: key: 'koa:sess',
2020-03-08T11:38:33.123092+00:00 app[web.1]: maxAge: 86400000,
2020-03-08T11:38:33.123092+00:00 app[web.1]: overwrite: true,
2020-03-08T11:38:33.123093+00:00 app[web.1]: httpOnly: true,
2020-03-08T11:38:33.123093+00:00 app[web.1]: signed: true,
2020-03-08T11:38:33.123093+00:00 app[web.1]: autoCommit: true,
2020-03-08T11:38:33.123093+00:00 app[web.1]: encode: [Function: encode],
2020-03-08T11:38:33.123094+00:00 app[web.1]: decode: [Function: decode],
2020-03-08T11:38:33.123094+00:00 app[web.1]: genid: [Function: v4]
2020-03-08T11:38:33.123094+00:00 app[web.1]: },
2020-03-08T11:38:33.123095+00:00 app[web.1]: store: undefined,
2020-03-08T11:38:33.123095+00:00 app[web.1]: session: [Circular],
2020-03-08T11:38:33.123095+00:00 app[web.1]: prevHash: 502277396
2020-03-08T11:38:33.123095+00:00 app[web.1]: },
2020-03-08T11:38:33.123095+00:00 app[web.1]: _ctx: {
2020-03-08T11:38:33.123096+00:00 app[web.1]: request: {
2020-03-08T11:38:33.123096+00:00 app[web.1]: method: 'GET',
2020-03-08T11:38:33.123097+00:00 app[web.1]: url: '/auth/callback?code=7f90a7c93ec4bdab5a163efe0f6674e9&hmac=74538170ef27af96b16b4b071949498c668615c1fe2a2e5c74af5b21d4c5d95f&shop=corporate-marquees.myshopify.com&state=158366751035400&timestamp=1583667512',
2020-03-08T11:38:33.123098+00:00 app[web.1]: header: [Object]
2020-03-08T11:38:33.123098+00:00 app[web.1]: },
2020-03-08T11:38:33.123098+00:00 app[web.1]: response: {
2020-03-08T11:38:33.123099+00:00 app[web.1]: status: 404,
2020-03-08T11:38:33.123099+00:00 app[web.1]: message: 'Not Found',
2020-03-08T11:38:33.123099+00:00 app[web.1]: header: [Object: null prototype] {}
2020-03-08T11:38:33.123099+00:00 app[web.1]: },
2020-03-08T11:38:33.123100+00:00 app[web.1]: app: { subdomainOffset: 2, proxy: false, env: 'production' },
2020-03-08T11:38:33.123100+00:00 app[web.1]: originalUrl: '/auth/callback?code=7f90a7c93ec4bdab5a163efe0f6674e9&hmac=74538170ef27af96b16b4b071949498c668615c1fe2a2e5c74af5b21d4c5d95f&shop=corporate-marquees.myshopify.com&state=158366751035400&timestamp=1583667512',
2020-03-08T11:38:33.123100+00:00 app[web.1]: req: '<original node req>',
2020-03-08T11:38:33.123101+00:00 app[web.1]: res: '<original node res>',
2020-03-08T11:38:33.123101+00:00 app[web.1]: socket: '<original node socket>'
2020-03-08T11:38:33.123101+00:00 app[web.1]: },
2020-03-08T11:38:33.123101+00:00 app[web.1]: shop: 'corporate-marquees.myshopify.com',
2020-03-08T11:38:33.123103+00:00 app[web.1]: accessToken: '9f770c310f6594f7156f49f15971b314',
2020-03-08T11:38:33.123103+00:00 app[web.1]: _expire: 1583753012090
2020-03-08T11:38:33.123103+00:00 app[web.1]: }
2020-03-08T11:38:33.121121+00:00 heroku[router]: at=info method=GET path="/auth/callback?code=7f90a7c93ec4bdab5a163efe0f6674e9&hmac=74538170ef27af96b16b4b071949498c668615c1fe2a2e5c74af5b21d4c5d95f&shop=corporate-marquees.myshopify.com&state=158366751035400&timestamp=1583667512" host=desolate-dusk-53030.herokuapp.com request_id=3c163b74-e952-43f4-aab0-03810df24949 fwd="120.22.148.184" dyno=web.1 connect=0ms service=192ms status=302 bytes=571 protocol=https
2020-03-08T11:38:34.013656+00:00 heroku[router]: at=info method=GET path="/" host=desolate-dusk-53030.herokuapp.com request_id=5824af27-2384-464c-881a-e27dc2cbd013 fwd="120.22.148.184" dyno=web.1 connect=0ms service=158ms status=200 bytes=2123 protocol=https
2020-03-08T11:38:34.014079+00:00 app[web.1]: getInitialProps undefined
2020-03-08T11:38:34.014342+00:00 app[web.1]: API_KEY 151556c6cc15c8cb53e36a2b31e4dbd3
2020-03-08T11:38:34.014392+00:00 app[web.1]: shopOrigin undefined
2020-03-08T11:38:35.063808+00:00 heroku[router]: at=info method=GET path="/_next/static/css/styles.e67fd66e.chunk.css" host=desolate-dusk-53030.herokuapp.com request_id=76716450-3ea8-49d6-9a10-d591874364e7 fwd="120.22.148.184" dyno=web.1 connect=0ms service=154ms status=304 bytes=316 protocol=https
2020-03-08T11:38:37.678159+00:00 heroku[router]: at=info method=GET path="/?hmac=d9de6aa043adf24ab4047221cfd02daa21bc5353ae68772401458fa6aaf37793&locale=en&session=9b31f483a771b5de57c2979ec71eb81d0d55b79371fd1f853ab703febb05d2a2&shop=corporate-marquees.myshopify.com&timestamp=1583667515" host=desolate-dusk-53030.herokuapp.com request_id=d18c711d-00e4-4cb5-8f3f-228c4ecbecb6 fwd="120.22.148.184" dyno=web.1 connect=0ms service=2ms status=302 bytes=311 protocol=https
2020-03-08T11:38:37.990705+00:00 heroku[router]: at=info method=GET path="/auth?shop=corporate-marquees.myshopify.com" host=desolate-dusk-53030.herokuapp.com request_id=88715773-9ab5-4a7d-a944-153272289b37 fwd="120.22.148.184" dyno=web.1 connect=0ms service=2ms status=200 bytes=1398 protocol=https
2020-03-08T11:38:38.404225+00:00 heroku[router]: at=info method=GET path="/auth/inline?shop=corporate-marquees.myshopify.com" host=desolate-dusk-53030.herokuapp.com request_id=c6cd9304-eca8-49a6-9944-8575b9ee47f9 fwd="120.22.148.184" dyno=web.1 connect=0ms service=4ms status=302 bytes=1482 protocol=https
2020-03-08T11:38:39.553067+00:00 heroku[router]: at=info method=GET path="/auth/callback?code=13fdfb79c8960389cb92207d3f8e4041&hmac=e7c6420b3ab2e2970db14ba6a0436d47dc248fd6cba6124e061b4eac1e9024b0&shop=corporate-marquees.myshopify.com&state=158366751840300&timestamp=1583667519" host=desolate-dusk-53030.herokuapp.com request_id=65a6e283-3055-47b0-b78e-82f47c0978aa fwd="120.22.148.184" dyno=web.1 connect=0ms service=173ms status=302 bytes=571 protocol=https`

Do you guys have some example project that it's currently working that you could share?

Thanks

**Comment by clucs123** [comment]
As you can get the app to work locally then versioning probably isn't the problem but I've noticed that this barebones project has some dependencies that are out of date. Below are the dependencies used on one of my published apps. Polaris and apollo-boost are newer versions

`"dependencies": {
    "@apollo/react-hooks": "^3.1.3",
    "@shopify/app-bridge": "^1.16.0",
    "@shopify/app-bridge-react": "^1.16.0",
    "@shopify/koa-shopify-auth": "^3.1.51",
    "@shopify/koa-shopify-graphql-proxy": "^3.3.0",
    "@shopify/koa-shopify-webhooks": "^2.2.2",
    "@shopify/polaris": "^4.10.2",
    "@zeit/next-css": "^1.0.1",
    "apollo-boost": "^0.4.7",
    "apollo-cache-inmemory": "^1.6.5",
    "apollo-link-http": "^1.5.16",
    "bull": "^3.12.1",
    "copy-to-clipboard": "^3.2.0",
    "core-js": "^3.6.1",
    "dotenv": "^8.2.0",
    "foreman": "^3.0.1",
    "gmail-send": "^1.8.10",
    "graphql": "^14.6.0",
    "highlight.js": "^9.17.1",
    "ioredis": "^4.14.1",
    "isomorphic-fetch": "^2.2.1",
    "js-cookie": "^2.2.1",
    "koa": "^2.11.0",
    "koa-body": "^4.1.1",
    "koa-router": "^7.4.0",
    "koa-session": "^5.12.3",
    "mailchimp-api-v3": "^1.13.1",
    "next": "^9.1.7",
    "next-routes": "^1.4.2",
    "node-fetch": "^2.6.0",
    "papaparse": "^5.1.1",
    "pg": "^7.17.0",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-apollo": "^3.1.3",
    "react-color": "^2.18.0",
    "react-csv-reader": "^2.0.2",
    "react-dom": "^16.12.0",
    "store-js": "^2.0.4",
    "throng": "^4.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.3",
    "eslint": "^6.8.0",
    "eslint-plugin-react": "^7.17.0",
    "eslint-plugin-react-hooks": "^2.3.0",
    "koa-webpack": "^5.3.0",
    "webpack-dev-middleware": "^3.7.2"
  }`

**Comment by clucs123** [comment]
I know it's obvious but have you changed the app settings in Shopify, ie the App Url and Callback URL from your ngrok to the Heroku URL?

**Comment by clucs123** [comment]
Unfortunately, this is the only project I can share at the moment. All the rest are published apps.

**Comment by xicovarisco** [comment]
> I know it's obvious but have you changed the app settings in Shopify, ie the App Url and Callback URL from your ngrok to the Heroku URL?

Yeah, I did.

**Comment by xicovarisco** [comment]
> As you can get the app to work locally then versioning probably isn't the problem but I've noticed that this barebones project has some dependencies that are out of date. Below are the dependencies used on one of my published apps. Polaris and apollo-boost are newer versions
> 
> `"dependencies": { "@apollo/react-hooks": "^3.1.3", "@shopify/app-bridge": "^1.16.0", "@shopify/app-bridge-react": "^1.16.0", "@shopify/koa-shopify-auth": "^3.1.51", "@shopify/koa-shopify-graphql-proxy": "^3.3.0", "@shopify/koa-shopify-webhooks": "^2.2.2", "@shopify/polaris": "^4.10.2", "@zeit/next-css": "^1.0.1", "apollo-boost": "^0.4.7", "apollo-cache-inmemory": "^1.6.5", "apollo-link-http": "^1.5.16", "bull": "^3.12.1", "copy-to-clipboard": "^3.2.0", "core-js": "^3.6.1", "dotenv": "^8.2.0", "foreman": "^3.0.1", "gmail-send": "^1.8.10", "graphql": "^14.6.0", "highlight.js": "^9.17.1", "ioredis": "^4.14.1", "isomorphic-fetch": "^2.2.1", "js-cookie": "^2.2.1", "koa": "^2.11.0", "koa-body": "^4.1.1", "koa-router": "^7.4.0", "koa-session": "^5.12.3", "mailchimp-api-v3": "^1.13.1", "next": "^9.1.7", "next-routes": "^1.4.2", "node-fetch": "^2.6.0", "papaparse": "^5.1.1", "pg": "^7.17.0", "prop-types": "^15.7.2", "react": "^16.12.0", "react-apollo": "^3.1.3", "react-color": "^2.18.0", "react-csv-reader": "^2.0.2", "react-dom": "^16.12.0", "store-js": "^2.0.4", "throng": "^4.0.0" }, "devDependencies": { "babel-eslint": "^10.0.3", "eslint": "^6.8.0", "eslint-plugin-react": "^7.17.0", "eslint-plugin-react-hooks": "^2.3.0", "koa-webpack": "^5.3.0", "webpack-dev-middleware": "^3.7.2" }`

I'll try to install these packages to see what happens

**Comment by xicovarisco** [comment]
Btw.. What commands do you use to 'start' and 'build' your project?

Either locally and on Heroku..

**Comment by clucs123** [comment]
"npm run dev" and "npm run build" locally. 

Heroku builds and restarts your app when you push to the git master. 

Btw, you don't need to install all the above packages as some are only relevant to the specific project. I know from experience though that there are issues with Polaris and apollo when the wrong combination of versions are used. I don't think that this is your problem here though as you can get it to work locally. 

Did you check your App Url and the Whitelist URL is Shopify is using your Heroku URL?

**Comment by TomGranot** [comment]
@xicovarisco repro'ing now, back in a few.

**Comment by xicovarisco** [comment]
> "npm run dev" and "npm run build" locally.
> 
> Heroku builds and restarts your app when you push to the git master.
> 
> Btw, you don't need to install all the above packages as some are only relevant to the specific project. I know from experience though that there are issues with Polaris and apollo when the wrong combination of versions are used. I don't think that this is your problem here though as you can get it to work locally.
> 
> Did you check your App Url and the Whitelist URL is Shopify is using your Heroku URL?

Yeah man, I checked.
Check it out my screenshot:

![B07A6C59-8DBA-4636-AD5A-ADA90ED16068](https://user-images.githubusercontent.com/2739233/76163360-1e9d5100-6191-11ea-9338-3cbe7fa32f2a.png)

**Comment by TomGranot** [comment]
Ah, interesting, first load of store after install crashed my tab. Console seems pissed at `shopOrigin` being missing:
![image](https://user-images.githubusercontent.com/8835035/76163497-41a71100-614f-11ea-99a4-db2ef0071d47.png)

So what happens after the authentication flow is complete is:
https://github.com/clucs123/shopify-react-test-v2/blob/master/server/server.js#L35

Meaning it redirects to its own root. If I'm not mistaken, this is the part where I'd expect it throws you back into the store's admin panel, i.e. the app is "locked into" an iFrame.

Let me try to unbrick the tab and see what gives.

**Comment by TomGranot** [comment]
But, assuming that the user hasn't left you in this state, and for some bizarre reason attempted to try and use the app from the admin panel (i.e. inside his store) - it does not redirect:
![image](https://user-images.githubusercontent.com/8835035/76163569-dd388180-614f-11ea-84ae-bf9ed43359eb.png)

So, in other words, can't repro. Note, by the way, that now the console is angry at the `apiKey` being missing, and not the `shopOrigin`.

I'd say, if this is indeed the default output of the shopify-app-cli (which I did not find to be very helpful for my workflow, since it has some nasty bugs), then a bug report is due.

Let's try and figure it out step by step though - I'll compare my working app with this to see where the different lies (I based mine a few months ago on https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react).

**Comment by clucs123** [comment]
@tomgs  I've experienced a similar problem in the past with retrieving the ShopOrigin and it was the ApolloClient that was the issue. Updating the versions of app-bridge, app-bridge-react and react-apollo sorted it out. I've checked this repo's dependencies and they are older than my current live projects.

**Comment by TomGranot** [comment]
This is my Heroku config BTW:
![image](https://user-images.githubusercontent.com/8835035/76163676-e6761e00-6150-11ea-91d6-2a790a80935c.png)

Let me just jot down for a second here some obvious differences from comparing the two pieces of boilerplate code in `server/server.js`. Below, `tut` is from the tutorial I mentioned above and `cli` is from the skeleton shopify-app-cli creates. The order is roughly the same as it appears in the file:

1. If no port is provided to the app via an environment variable, `tut` spins up on 3000 and `cli` spins up on `8081`.
1.  The `koa-session` middleware is provided with `secure` and `sameSite` cookie attributes to deal with [a recent Chrome update](https://shopify.dev/tutorials/migrate-your-app-to-support-samesite-cookies) in `tut` but not in `cli`.
1. `afterAuth` is declared `async` in `cli` but not in `tut`.

That seems to be about it. Also, I literally just saw @clucs123's comment on updating the deps, so I'll do that as well and be back in a blast.

**Comment by TomGranot** [comment]
Ah, so `app-bridge-react` I'm running is actually _older_ than the one in this repo here, and I'm running a later Apollo and a later `react-apollo`. Let me match those and re-deploy to Heroku.

**Comment by clucs123** [comment]
This is the _app.js file from the project I took above dependencies from. It might help as it's different to the file in this repo. The way to configure the Apollo client is different in more recent versions.

`import App from "next/app";
import Head from "next/head";
import { AppProvider, Frame } from "@shopify/polaris";
import { Provider } from "@shopify/app-bridge-react";
import "@shopify/polaris/styles.css";
import { ApolloProvider } from "react-apollo";
import React from "react";
import fetch from "node-fetch";
import Cookies from "js-cookie";

import { ApolloClient } from 'apollo-client';
import { HttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory';

const link = new HttpLink({
  uri: `${Cookies.get("host")}/graphql`,
  credentials: 'include',
  fetch: fetch
});

const client = new ApolloClient({
  link,
  cache: new InMemoryCache()
});

class MyApp extends App {

  render() {
    const { Component, pageProps } = this.props;

    const config = {
      // eslint-disable-next-line no-undef
      apiKey: API_KEY,
      shopOrigin: Cookies.get("shopOrigin"),
      forceRedirect: true
    };

    return (
      <React.Fragment>
        <Head>
          <title>APP TITLE GOES HERE</title>
          <meta charSet="utf-8" />
        </Head>
        <Provider config={config}>
          <AppProvider>
            <Frame>
              <ApolloProvider client={client}>
                <Component {...pageProps} />
              </ApolloProvider>
            </Frame>
          </AppProvider>
        </Provider>
      </React.Fragment>
    );
  }
}

export default MyApp;`

**Comment by TomGranot** [comment]
@clucs123 formatting? :)

**Comment by TomGranot** [comment]
Ah, so updating the deps gives me a `500` now: 
```
2020-03-08T13:38:09.023801+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=shopify-react-testing.herokuapp.com request_id=2975d2ce-d691-496a-a54d-a84e59ae918f fwd="87.70.6.177" dyno=web.1 connect=1ms service=114ms status=302 bytes=296 protocol=https
2020-03-08T13:38:09.222975+00:00 app[web.1]: 
2020-03-08T13:38:09.223078+00:00 app[web.1]:   TypeError: option sameSite is invalid
2020-03-08T13:38:09.223079+00:00 app[web.1]:       at new Cookie (/app/node_modules/cookies/index.js:146:11)
2020-03-08T13:38:09.223080+00:00 app[web.1]:       at Cookies.set (/app/node_modules/cookies/index.js:88:16)
2020-03-08T13:38:09.223081+00:00 app[web.1]:       at topLevelOAuthRedirect (/app/node_modules/@shopify/koa-shopify-auth/dist/src/auth/create-top-level-oauth-redirect.js:10:21)
2020-03-08T13:38:09.223081+00:00 app[web.1]:       at /app/node_modules/@shopify/koa-shopify-auth/dist/src/auth/index.js:53:46
2020-03-08T13:38:09.223082+00:00 app[web.1]:       at step (/app/node_modules/tslib/tslib.js:133:27)
2020-03-08T13:38:09.223082+00:00 app[web.1]:       at Object.next (/app/node_modules/tslib/tslib.js:114:57)
2020-03-08T13:38:09.223082+00:00 app[web.1]:       at /app/node_modules/tslib/tslib.js:107:75
2020-03-08T13:38:09.223083+00:00 app[web.1]:       at new Promise (<anonymous>)
2020-03-08T13:38:09.223084+00:00 app[web.1]:       at Object.__awaiter (/app/node_modules/tslib/tslib.js:103:16)
2020-03-08T13:38:09.223084+00:00 app[web.1]:       at shopifyAuth (/app/node_modules/@shopify/koa-shopify-auth/dist/src/auth/index.js:34:24)
2020-03-08T13:38:09.223137+00:00 app[web.1]: 
```

Don't really have time to go deeper into this right now, I'm afraid. I'd go through https://github.com/Shopify/shopify-demo-app-node-react, which is the official app for the tutorial I mentioned above ((https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react), and see what gives @xicovarisco.

@clucs123 per your comment (again beating me to the punch!) - I actually mentioned it in a previous comment and aware of the topic, thanks.

I'll come back around if I have a bit more time tonight and it's not resolved.

**Comment by clucs123** [comment]
@tomgs have you checked out this page on Shopify regarding the samesite issue. 

[https://shopify.dev/tutorials/migrate-your-app-to-support-samesite-cookies]

**Comment by xicovarisco** [comment]
Thanks for all the tips @clucs123 and @tomgs.
I didn't know we could use the CLI to create new projects, so possibly it's a great start point for me.

Shopify needs to up their game in terms of documentation for developers if they want to have thriving app store, that's for sure.

Will ping you guys here on how it goes

**Comment by xicovarisco** [comment]
Ok. It's finally working here!! HURRAY 🎉

Honestly, I don't know what's makes the difference between what I have now and I had before.
The fact is, I've started the project differently (Which I wish I knew before). Before I have started my project basing myself on the official react shopify example. Right now I've started the project from the Shopify CLI.
The CLI installed all the dependencies I needed to install to get started (And apparently installed the proper package versions from all the repos).

Steps I did to get that done:
* Created the project via Shopify CLI. 
* Created a new project on Heroku for this new project
* Configured the env variables on Heroku pointing to my Shopify Partners App
* Changed the whitelisted url and host on my Shopify Partners App
* Uninstalled my previous app from my store
* Pushed a version of my app to heroku
* Installed the app again with my unique link

I'm almost sure you guys know these steps already, but as I'm new to Shopify I wish I had before. :)

But anyway... happy days now :)

**Comment by clucs123** [comment]
@xicovarisco Yes, the CLI is a quick and easy way to get started, I had a play around with it when it was released last year. I'm glad you got it sorted :)

**Comment by TomGranot** [comment]
@xicovarisco awesome! Happy you made it happen.

Two points worth mentioning:

1. The whole `npm run dev`, `npm run start` and actually `npm run X` for every `X` imaginable are called "Scripts" and are little keywords that are aliases for various commands. They are defined inside `pacakage.json` and are part of the Node.js + npm ecosystem. Read more about them here: https://docs.npmjs.com/files/package.json#scripts. Specifically, they are editable, and most devs I know either use a bunch of pre-defined ones based on the packages they use (like `npm run lint` to lint, and `npm run test` to run a d test suite), and sometimes even write their own if the need arises (like when you want to add a prefix to some command that is not an existing script in your `package.json` file). The entire Shopify app development process (or, more accurately, the ones they're pushing with the `shopify-app-cli`) revolves heavily around that ecosystem. Some resources you might find helpful:

- The Node.js dev site's [Intro to Node.js](https://nodejs.dev/introduction-to-nodejs) will give you a path through the woods
- Flavio Copes's [React](https://flaviocopes.com/page/react-handbook/) and [Next](https://flaviocopes.com/page/nextjs-handbook/) books (free!) will get you far enough to become productive
 
2. Do not over-use the Shopify's CLI tunnel capabilities, to avoid getting hit with "Too Many Connections" with `ngrok` - see https://github.com/Shopify/shopify-app-cli/issues/449 for details. I scaffold with the CLI (meaning I let it build the directory) but run `ngrok http XXXX` myself and not through the CLI. Never once hit the `too many connections` problem.
